img_num: 3
recover_time: 10
camera: 'picamera'
google_secret: 'mycreds.txt'
twitter_secret: 'twitter_api.yml'
m_pin: 26
twitter_limit: 1

targets: ['person','bird','dog','deer']
location: 'Raleigh, NC'
id: 'PCT_alpha'
confidence_threshold: 0.1

publish_topic: 'berrynet/event/localImage'
subscribe_topic: 'berrynet/dashboard/inferenceResult'
